# Generated by Django 3.2.9 on 2021-12-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211201_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
