# Generated by Django 3.2.8 on 2021-10-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('title', models.TextField(default='Basic_Full_Body')),
                ('description', models.TextField(default='lorem ipsum')),
                ('place', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('name', models.TextField(default='user')),
                ('expereience_level', models.IntegerField(default=0)),
                ('is_trainer', models.BooleanField(default=True)),
            ],
        ),
    ]
