# Generated by Django 3.2.8 on 2021-10-25 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_user_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='expereience_level',
            new_name='experience_level',
        ),
        migrations.AddField(
            model_name='plan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
