# Generated by Django 3.2.8 on 2021-10-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20211025_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='builder.user'),
            preserve_default=False,
        ),
    ]
