# Generated by Django 3.2.8 on 2021-12-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_plan_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='place',
            new_name='location',
        ),
    ]
