# Generated by Django 3.2.8 on 2021-12-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_rename_place_plan_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='fe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='fe'),
            preserve_default=False,
        ),
    ]
